name: Checks, Lints and Unit Tests
on:
  push:
    paths:
      - frontend/**
  pull_request:
    paths:
      - frontend/**

defaults:
  run:
    working-directory: frontend

env:
  VITE_APP_API_URL: http://localhost:8000
  VITE_APP_QR_CODE_URL: http://localhost:5173

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run type checks
        run: npm run typecheck

      - name: Run linting
        run: npm run lint

      - name: Run unit tests
        run: npm run test
